### ISSUE TITLE
register

### ISSUE THREAD

**Issue by PlayA2137** [anditv21/znixv2-panel-edit-edit#28]
When you try to register, you get HTTP ERROR 500, all files rights in ftp are turned 777.

Can someone help me with this?

**Comment by anditv21** [comment]
Could you give me some more details about the error?
Can you read the exact error in the php error log?
Did you enable or disable the invite system?

**Comment by PlayA2137** [comment]
"The server cannot handle this request." I tried with enabled and disabled invite system.

**Comment by PlayA2137** [comment]
"The server cannot handle this request." I tried with enabled and disabled invite system.

**Comment by anditv21** [comment]
> "The server cannot handle this request." I tried with enabled and disabled invite system.

Please try this:
1. Delete the .htaccess file
2. Waiting about 3 minutes
3. (if u still get the error) Set all permissions to 775

**Comment by PlayA2137** [comment]
I deleted htacces because it block access to site, i tried with database from original znix and register works but login got https 500 error, I would try with 775.

**Comment by anditv21** [comment]
Unfortunately, the db.sql from the original panel does not work with my panel edit..

**Comment by PlayA2137** [comment]
Yeah I know.

**Comment by anditv21** [comment]
So you still get the same error with my db.sql and you have already tried all the steps?

**Comment by PlayA2137** [comment]
Yeah all files to 775, I imported DB again, sec I will re upload files to host.

**Comment by PlayA2137** [comment]
okay didnt work all. I dont know whats going on but i think its ftp bad

**Comment by anditv21** [comment]
Unfortunately I can't do anything with the error message you get. And I can't reproduce this error.

Did you also follow all the steps from https://github.com/anditv21/znixv2-panel-edit-edit#Setup?
Also renamed the files?

Have you perhaps overlooked that you are in the standard configuration
need to use the panel in a sub folder?(https://github.com/anditv21/znixv2-panel-edit-edit/blob/main/app/core/Config.php)

**Comment by anditv21** [comment]
Do you have access to the php error log?
If not are you using nginx or apache?
